# Generated by Django 5.0.7 on 2024-07-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('name', models.CharField(max_length=200)),
                ('age', models.DateField()),
                ('skills', models.CharField(max_length=200)),
                ('city', models.TextField(default='Tehran')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
